name: anova_incomings
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.14.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_secure_storage: ^9.2.2
  flutter_session_jwt: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
