name: anova_incomings
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.14.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_secure_storage: ^9.2.2
  flutter_session_jwt: ^0.0.6
  http: ^1.2.1
  money_formatter: ^0.0.6
  provider: ^6.1.2
  retrofit: ^4.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
